#!/usr/bin/env python3
"""Validate the skills library and regenerate skills/INDEX.md.

Checks:
  - frontmatter: name == folder name, description present and <= 1024 chars
  - every `references/` / `assets/` path mentioned in a SKILL.md exists
  - every file under references/ and assets/ is mentioned in its SKILL.md
  - every `founder-os-*` mention resolves to an existing skill
  - SKILL.md has a Depends on / Feeds line; non-context skills mention founder-os-context
  - examples/ reuse only IDs (T-/D-/P-/C-) that are defined in the example context.md

Usage: python -I scripts/validate.py [--write-index]
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKILLS = ROOT / "skills"
GROUPS = {
    "Foundation": ["context"],
    "Product & Engineering": ["research", "pm", "roadmap", "metrics", "design-artifacts",
                              "architect", "lld", "data-model"],
    "Go-to-market": ["market", "positioning", "content", "launch", "sales"],
}
PREFIX = "founder-os-"


def frontmatter(text):
    m = re.match(r"---\n(.*?)\n---\n", text, re.S)
    if not m:
        return {}
    return dict(re.findall(r"^(\w+): (.*)$", m.group(1), re.M))


def main():
    errors = []
    names = {d.name for d in SKILLS.iterdir() if d.is_dir()}
    meta = {}
    for d in sorted(SKILLS.iterdir()):
        if not d.is_dir():
            continue
        md = d / "SKILL.md"
        if not md.exists():
            errors.append(f"{d.name}: missing SKILL.md")
            continue
        text = md.read_text(encoding="utf-8")
        fm = frontmatter(text)
        meta[d.name] = fm
        if fm.get("name") != d.name:
            errors.append(f"{d.name}: frontmatter name {fm.get('name')!r} != folder")
        desc = fm.get("description", "")
        if not desc:
            errors.append(f"{d.name}: empty description")
        elif len(desc) > 1024:
            errors.append(f"{d.name}: description {len(desc)} chars > 1024")
        if "**Depends on:**" not in text:
            errors.append(f"{d.name}: missing Depends on / Feeds line")
        if d.name != PREFIX + "context" and PREFIX + "context" not in text:
            errors.append(f"{d.name}: never mentions {PREFIX}context")
        mentioned = set(re.findall(r"(?<![\w/\-])(?:references|assets)/[\w.\-]+", text))
        for ref in mentioned:
            if not (d / ref).exists():
                errors.append(f"{d.name}: references missing file {ref}")
        for sub in ("references", "assets"):
            for f in (d / sub).glob("*") if (d / sub).exists() else []:
                if f"{sub}/{f.name}" not in text:
                    errors.append(f"{d.name}: orphan file {sub}/{f.name} (not linked)")
        for other in set(re.findall(r"founder-os-[a-z\-]+", text)):
            if other not in names:
                errors.append(f"{d.name}: mentions unknown skill {other}")

    # example ID consistency
    ctx = ROOT / "examples" / "northwind-pulse" / "context.md"
    if ctx.exists():
        defined = set(re.findall(r"\b([TDPC]-\d{3})\b", ctx.read_text(encoding="utf-8")))
        for f in (ctx.parent).glob("*"):
            if f.is_file() and f != ctx:
                for i in set(re.findall(r"\b([TDPC]-\d{3})\b", f.read_text(encoding="utf-8"))):
                    if i not in defined:
                        errors.append(f"{f.relative_to(ROOT)}: ID {i} not defined in context.md")

    if "--write-index" in sys.argv:
        lines = ["# Skills index", "",
                 "Generated by `scripts/validate.py --write-index`. Do not edit by hand.", ""]
        for group, members in GROUPS.items():
            lines += [f"## {group}", "", "| Skill | Description |", "|---|---|"]
            for m in members:
                n = PREFIX + m
                d = meta.get(n, {}).get("description", "")
                short = re.split(r"\. Use this skill", d)[0].replace("|", "/")
                lines.append(f"| [{n}]({n}/SKILL.md) | {short} |")
            lines.append("")
        (SKILLS / "INDEX.md").write_text("\n".join(lines), encoding="utf-8", newline="\n")

    for e in errors:
        print("ERROR:", e)
    print(f"{len(meta)} skills checked, {len(errors)} error(s)")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
